import { StyleSheet } from "aphrodite";

export const pokemonTypeColors = StyleSheet.create({
    General:{
        color:"white",
        padding:"5px 10px",
        marginLeft:"10px",
        borderRadius:"10px"
    },
    Grass:{
        backgroundColor:"#78C850",
    },
    Fire:{
        backgroundColor:"#F08030",
    },
    Water:{
        backgroundColor:"#6890F0",
    },
    Bug:{
        backgroundColor:"#A8B820",
    },
    Normal:{
        backgroundColor:"#A8A878",
    },
    Poison:{
        backgroundColor:"#A040A0",
    },
    Electric:{
        backgroundColor:"#F8D030",
    },
    Ground:{
        backgroundColor:"#E0C068",
    },
    Fairy:{
        backgroundColor:"#EE99AC",
    },
    Fighting:{
        backgroundColor:"#C03028",
    },
    Psychic:{
        backgroundColor:"#F85888",
    },
    Rock:{
        backgroundColor:"#B8A038",
    },
    Ghost:{
        backgroundColor:"#705898",
    },
    Ice:{
        backgroundColor:"#98D8D8",
    },
    Dragon:{
        backgroundColor:"#7038F8",
    },
    Dark:{
        backgroundColor:"#5E514B"
    },
    Steel:{
        background:"#D3CBD4"
    },
    Flying:{
        backgroundColor:"#C05BC7"
    }
})